apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    control-plane.alpha.kubernetes.io/leader: '{"holderIdentity":"nginx-nginx-ingress-controller-6c76b87854-rt82p","leaseDurationSeconds":30,"acquireTime":"2021-01-12T03:16:58Z","renewTime":"2021-01-12T05:09:02Z","leaderTransitions":0}'
  creationTimestamp: "2021-01-12T03:16:58Z"
  name: ingress-controller-leader-nginx
  namespace: nginx
  resourceVersion: "34756"
  selfLink: /api/v1/namespaces/nginx/configmaps/ingress-controller-leader-nginx
  uid: 4f3ac931-3325-415f-bb37-b4240f7cf2e1
